name: "Run Leia Action"
description: "A GitHub Action for running Leia tests."
branding:
  color: purple
  icon: package
inputs:
  # Required
  leia-test:
    description: "The Leia test file to parse and run."
    required: true

  # Optional
  debug:
    description: "Turn on debug mode."
    required: false
    default: false
  cleanup-header:
    description: "The cleanup headers to parse."
    required: false
    default: "Clean,Tear,Burn"
  retry:
    description: "The amount of times to retry the test."
    required: false
    default: 1
  setup-header:
    description: "The setup headers to parse."
    required: false
    default: "Start,Setup,This is the dawning"
  stdin:
    description: "Attach stdin when the tests are run."
    default: false
    required: false
  test-header:
    description: "The test headers to parse."
    required: false
    default: "Test,Validat,Verif"
  version:
    description: "The fallback global version of Leia to install if no local version is detected."
    required: false
    default: "latest"

runs:
  using: composite
  steps:
    - name: Validate required inputs
      shell: bash
      run: |
        if [ "${{ inputs.leia-test }}" == "" ]; then
          echo "::error title=leia-test is not set!::You must specify a test file to parse and run."
          exit 10
        fi

        if [ ! -f "${{ inputs.leia-test }}" ]; then
          echo "::error title=Could not find ${{ inputs.leia-test }}!::${{ inputs.leia-test }} does not seem to exist."
          exit 11
        fi

    - name: Install node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: Add local bin to PATH
      shell: bash
      run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
    - name: Ensure Leia is installed
      shell: bash
      run: |
        if ! leia --version &>/dev/null; then
          echo "::group::Globally installing @lando/leia@${{ inputs.version }}"
          npm install --global @lando/leia@${{ inputs.version }}
          echo "::endgroup::"
        fi

        if ! leia --version &>/dev/null; then
          echo "::error title=Cannot run leia::Cannot seem to find the Leia binary!"
          exit 11
        fi
    - name: Run Leia tests
      shell: bash
      run: |
        echo "::group::Leia information"
          echo "bin: $(which leia)"
          echo "version: $(leia --version)"
        echo "::endgroup::"

        OPTS=
        if [ "${{ inputs.stdin }}" == "true" ]; then
          OPTS="--stdin"
        fi
        if [ "${{ inputs.debug }}" == "true" ]; then
          OPTS="$OPTS --debug"
        fi

        leia ${{ inputs.leia-test }} \
          --setup-header="${{ inputs.setup-header }}" \
          --test-header="${{ inputs.test-header }}" \
          --cleanup-header="${{ inputs.cleanup-header }}" \
          --retry=${{ inputs.retry }} $OPTS

