name: Options Tests

on:
  pull_request:

jobs:
  run-leia-options-tests:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        with:
          - leia-test: ./tests/TEST4.md
            debug: true
            cleanup-header: Clean,Tear,Burn,Destroy
            retry: 0
            setup-header: "Start,Setup,This is the dawning,So it begins!"
            stdin: true
            test-header: Test,Validat,Verif,Testing 1 2 3
            version: "^0.6.5"
          - leia-test: ./tests/TEST1.md
            runtime: node
          - leia-test: ./tests/TEST8.md
            runtime: bun
            bun-version: "1.3.5"


    steps:
      - name: Checkout action code
        uses: actions/checkout@v4
      - name: Run Leia Action
        uses: ./
        with:
          ${{ matrix.with }}
